/// 366 frases — uma por dia do ano (bissexto incluso), indexadas pelo
/// dia-do-ano. Determinístico: o mesmo dia mostra a mesma frase o dia
/// inteiro e troca à meia-noite. Teste garante 366 itens únicos.
const frasesDoDia = <String>[
  // 1-10 · constância
  'Constância vence intensidade. Um bloco de cada vez.',
  'O streak não se quebra sozinho: proteja-o.',
  'Aprovado é quem continua quando ninguém vê.',
  'Um dia de cada vez, com método.',
  'Estudar todo dia um pouco vence estudar muito de vez em quando.',
  'A regularidade é o único atalho que existe.',
  'Hoje conta. Amanhã também vai contar.',
  'Quem não falha dois dias seguidos nunca sai do jogo.',
  'Pequeno progresso diário vira vantagem enorme em um ano.',
  'A rotina que você repete é o futuro que você constrói.',
  // 11-20 · revisão e memória
  'Revisar vale mais que avançar sem reter.',
  'Página lida sem revisão é página emprestada.',
  'Quem revisa duas vezes erra metade.',
  'Memória não é dom: é revisão espaçada.',
  'O que você revisou hoje é o que você lembra na prova.',
  'Revisão atrasada cobra juros.',
  'Reler não é revisar. Revise ativamente: se teste.',
  'O esquecimento é normal; revisar é a resposta.',
  'Conteúdo novo empolga, revisão aprova.',
  'A terceira revisão é onde o conteúdo vira seu.',
  // 21-30 · questões e prática
  'Questões erradas hoje são pontos ganhos na prova.',
  'A banca cobra o básico bem feito. Faça o básico hoje.',
  'A banca repete. Quem faz questões antigas chega em casa conhecida.',
  'Teoria sem questão é mapa sem viagem.',
  'Cada questão errada te mostra exatamente o que estudar.',
  'Resolver questão é conversar com a banca.',
  'Acertar em casa não vale nada; entender o erro vale tudo.',
  'Dez questões por dia mantêm a ferrugem longe.',
  'Quem treina sob pressão não congela na prova.',
  'O caderno de erros é o material mais valioso que você tem.',
  // 31-40 · edital e estratégia
  'Edital não assusta quem tem ciclo.',
  'O edital é o contrato: estude o que está nele, não o que você gosta.',
  'Peso de matéria existe para ser respeitado.',
  'Estude a matéria que você evita: é onde mora a diferença.',
  'Conhecer a banca vale um mês de estudo.',
  'Prova passada é o melhor professor do edital.',
  'Não existe matéria difícil, existe matéria mal dosada no ciclo.',
  'A vaga sai para quem estuda o edital inteiro, não a metade favorita.',
  'Estratégia é dizer não para o conteúdo fora do edital.',
  'Quem domina o edital não se surpreende no dia da prova.',
  // 41-50 · foco
  'Menos redes, mais horas líquidas.',
  'Meia hora focada vale mais que três horas com o celular do lado.',
  'Foco é escolher o que NÃO fazer agora.',
  'Celular no outro cômodo: aprovação mais perto.',
  'Multitarefa é a arte de fazer duas coisas mal.',
  'A notificação pode esperar; a vaga não espera.',
  'Ambiente arrumado, mente focada.',
  'Cada aba aberta é um pedaço da sua atenção.',
  'Silencie o mundo por 50 minutos e veja o que acontece.',
  'Profundidade vence quantidade: uma hora imersa rende por três.',
  // 51-60 · sono, descanso e saúde
  'Dormir bem é estudar dormindo: a memória consolida à noite.',
  'Descanso planejado não é preguiça, é estratégia.',
  'Corpo cansado, memória fraca. Cuide da máquina.',
  'Pausa de dez minutos salva a hora seguinte.',
  'Estudar exausto é gravar em disco cheio.',
  'Água, comida de verdade e sono: o tripé invisível da aprovação.',
  'Um passeio curto desembaça a mente melhor que café.',
  'Domingo de descanso consciente vale mais que domingo de culpa.',
  'Treino físico é dopamina grátis para a maratona de estudos.',
  'Quem respeita o próprio limite dura até a posse.',
  // 61-70 · simulados e prova
  'Simulado ruim é diagnóstico grátis.',
  'Errar aqui é barato. Errar na prova custa um ano.',
  'Simulado é ensaio geral: leve a sério o relógio.',
  'Tempo por questão se treina, não se improvisa.',
  'A prova começa no edital e termina na revisão da véspera.',
  'Nervosismo é energia mal direcionada: canalize para a leitura atenta.',
  'Quem já errou tudo no simulado não tem o que temer na prova.',
  'Leia o comando duas vezes; a pegadinha mora na pressa.',
  'Chute com método também é técnica de prova.',
  'A prova não mede quem você é, mede o que você treinou.',
  // 71-80 · longo prazo e vaga
  'Nota de corte é consequência, não meta. Meta é o ciclo de hoje.',
  'A vaga é de quem transforma cansaço em constância.',
  'Seu eu de amanhã agradece a sessão de hoje.',
  'A posse é a soma de centenas de dias comuns.',
  'Ninguém lembra dos sábados que você estudou. Você lembrará da posse.',
  'O concurso é uma maratona com linha de chegada real.',
  'Cada edital adiado é tempo extra de preparo para quem estuda.',
  'A estabilidade que você quer custa a rotina que você evita.',
  'Pense na vaga uma vez por dia; no ciclo, o dia inteiro.',
  'Daqui a um ano você vai querer ter começado hoje. Você começou.',
  // 81-90 · disciplina
  'Disciplina é escolher o que você quer MAIS.',
  'Hoje estudado é ansiedade de amanhã reduzida.',
  'Motivação abre a porta; disciplina mora na casa.',
  'Não negocie com a preguiça: ela sempre pede desconto.',
  'O cronômetro ligado é uma decisão, não um sentimento.',
  'Faça antes de sentir vontade; a vontade vem no meio.',
  'Disciplina é lembrar do porquê quando o como cansa.',
  'Adiar quinze minutos vira adiar o dia. Comece torto, mas comece.',
  'O hábito carrega você nos dias em que a vontade falta.',
  'Quem só estuda inspirado estuda pouco.',
  // 91-100 · método e planejamento
  'Quem mede, melhora. Registre a sessão.',
  'Ritmo sustentável > maratona de véspera.',
  'Plano semanal no papel, cabeça livre para estudar.',
  'Ciclo de estudos existe para você nunca decidir "o que estudar agora".',
  'Meta de horas sem meta de conteúdo é meio plano.',
  'Ajuste o plano aos dados, não ao humor.',
  'O melhor método é o que você consegue repetir por meses.',
  'Priorize por peso e por fraqueza, não por afinidade.',
  'Sexta é dia de fechar o ciclo, não de abrir exceção.',
  'Semana boa se desenha no domingo.',
  // 101-110 · ansiedade e mente
  'Ansiedade diminui com ação: abra o material.',
  'Você não precisa dar conta de tudo hoje. Só do bloco de agora.',
  'Compare-se com o seu eu de ontem, não com o gabarito alheio.',
  'Pensamento catastrófico não resolve questão. Resolver questão sim.',
  'Respira. Uma sessão de cada vez.',
  'O medo de não passar diminui a cada hora líquida.',
  'Mente ruminando? Escreva a preocupação e volte ao estudo.',
  'Não deixe uma manhã ruim virar um dia perdido.',
  'Autocrítica em excesso é procrastinação disfarçada.',
  'Confiança se constrói com evidência: olhe seu histórico de horas.',
  // 111-120 · concorrência
  'Seu concorrente também está cansado.',
  'Enquanto você revisa, metade da concorrência desiste em silêncio.',
  'A fila anda para quem continua nela.',
  'Não subestime você: a maioria estuda menos do que diz.',
  'Concorrente de verdade é o seu próprio desperdício de tempo.',
  'Muita gente inscrita, pouca gente preparada.',
  'A nota de corte é feita por pessoas — seja a que estudou hoje.',
  'Quem estuda no feriado ultrapassa quem só estuda quando dá.',
  'A vaga não vai para o mais inteligente, vai para o mais constante.',
  'Cada sessão sua é um degrau que a concorrência não subiu.',
  // 121-130 · erro e aprendizado
  'Erro anotado é erro que não se repete.',
  'Errar em voz alta ensina mais que acertar calado.',
  'Quem nunca zera um assunto nunca descobriu onde melhorar.',
  'A dor do erro dura minutos; a lição, para sempre.',
  'Revisitar o erro de ontem é o estudo mais rentável de hoje.',
  'Não esconda a fraqueza no fim do ciclo: ataque-a primeiro.',
  'Errar cedo é privilégio de quem começou cedo.',
  'O gabarito errado de hoje é o reflexo condicionado de amanhã.',
  'Falhar um dia é dado; falhar a semana é decisão.',
  'Cada correção honesta vale por duas aulas.',
  // 131-140 · começo e recomeço
  'Começar de novo também é progresso.',
  'O melhor momento era ontem; o segundo melhor é agora.',
  'Voltar depois de uma pausa exige coragem — e você voltou.',
  'Não espere segunda-feira: o edital não espera.',
  'Página um de novo? Ótimo: agora você lê com outros olhos.',
  'Recomeçar não apaga o que você já aprendeu.',
  'Todo expert já foi um iniciante que não parou.',
  'A primeira sessão do dia é a mais difícil. Vença-a cedo.',
  'Um começo imperfeito vale mais que um plano perfeito parado.',
  'Se o dia começou errado, comece o dia de novo às 14h.',
  // 141-150 · tempo e priorização
  'Você não acha tempo, você toma tempo de algo menos importante.',
  'Quinze minutos existem em qualquer dia. Use-os.',
  'O tempo passa igual para todos; o uso é que aprova.',
  'Agenda cheia é questão de prioridade, não de horas.',
  'Corte trinta minutos de tela e ganhe um capítulo.',
  'Hora marcada para estudar é compromisso com a vaga.',
  'Quem espera sobrar tempo estuda com as sobras.',
  'Madrugar ou virar a noite não importa: importa a soma da semana.',
  'Tempo de deslocamento é tempo de lei seca em áudio.',
  'A semana tem 168 horas. A vaga pede 30 bem usadas.',
  // 151-160 · identidade e hábito
  'Você não "tenta passar": você é concurseiro em preparação.',
  'Aja como quem já tem rotina de aprovado.',
  'Hábito não pede motivação, pede gatilho e horário.',
  'O que você faz às 6h define o que você sente às 22h.',
  'Identidade vem antes do resultado: estude como quem passa.',
  'Seja a pessoa que a sua meta exige.',
  'Rotina chata é o uniforme dos aprovados.',
  'Quem se organiza uma vez decide uma vez só.',
  'Pequenos rituais protegem grandes objetivos.',
  'Você vira o que repete. Repita estudo.',
  // 161-170 · pequenos passos
  'Um tópico por dia fecha o edital antes do que parece.',
  'Grande edital, pequenas mordidas.',
  'O bloco de 25 minutos é pequeno demais para dar medo.',
  'Não dá para revisar tudo hoje. Dá para revisar um assunto.',
  'A escada inteira assusta; o degrau, nunca.',
  'Termine a página. Depois decida se continua.',
  'Meta mínima cumprida é vitória registrada.',
  'Dia cheio? Sessão curta. Dia livre? Sessão longa. Nunca zero.',
  'Cada linha do resumo é um tijolo da aprovação.',
  'Progresso invisível ainda é progresso.',
  // 171-180 · registro e medição
  'O que não é registrado não é gerenciado.',
  'Seu histórico de horas é seu retrato honesto.',
  'Dados não mentem: veja onde suas horas realmente vão.',
  'Registrar a sessão fecha o ciclo do esforço.',
  'A média diária conta uma história que a memória distorce.',
  'Sem registro, todo mundo "estuda muito".',
  'Gráfico subindo é o melhor motivador que existe.',
  'Meça o acerto por matéria e o plano se faz sozinho.',
  'Streak é métrica de caráter, não de vaidade.',
  'Quem anota o erro duas vezes não erra a terceira.',
  // 181-190 · equilíbrio teoria/prática
  'Teoria orienta, questão consolida, revisão eterniza.',
  'PDF fechado sem questões é conhecimento em quarentena.',
  'Alterne: leia de manhã, resolva à tarde, revise à noite.',
  'A proporção muda com a proximidade da prova: mais questão, menos PDF.',
  'Ler de novo é conforto; testar-se é crescimento.',
  'Aula é começo de estudo, não estudo completo.',
  'Resumo bom é o que você consegue reescrever de cabeça.',
  'Flashcard vence releitura em qualquer placar.',
  'Quem só assiste aula assiste a aprovação dos outros.',
  'Feche o livro e explique em voz alta: é aí que aprende.',
  // 191-200 · reta final
  'Reta final: revisar o certo, não abraçar o novo.',
  'Véspera é dia de sono, não de heroísmo.',
  'Nas últimas semanas, a lei seca vale ouro.',
  'Ajuste fino: menos volume, mais precisão.',
  'A prova se ganha nos 30 dias anteriores — com calma.',
  'Reta final sem pânico é diferencial competitivo.',
  'Reduza o escopo, aumente a profundidade.',
  'Última semana: só erro recorrente e letra de lei.',
  'Confie no material que você já tem.',
  'Quem chega descansado pensa melhor que quem chega inchado de conteúdo.',
  // 201-210 · dias ruins
  'Dia ruim de estudo ainda soma. Zero é o único fracasso.',
  'Rendimento baixo hoje? Amanhã compensa. Desistir não compensa nunca.',
  'Não romantize o cansaço, mas não o ignore: doses menores, mesmo ritmo.',
  'A sessão medíocre de hoje mantém viva a excelente de amanhã.',
  'Estude triste mesmo. A tristeza passa, o conteúdo fica.',
  'Perdoe o ontem improdutivo cumprindo o hoje.',
  'Todo aprovado tem semanas das quais não se orgulha.',
  'O plano aguenta um dia ruim; não aguenta o abandono.',
  'Chuva lá fora, ciclo em dia aqui dentro.',
  'Nem todo dia rende; todo dia conta.',
  // 211-220 · leitura e material
  'Menos materiais, mais passadas no mesmo material.',
  'Trocar de curso toda semana é recomeçar toda semana.',
  'O material perfeito é o que você termina.',
  'Marque menos, resuma mais.',
  'Grifo sem critério é decoração.',
  'Leia com pergunta na cabeça: o texto responde melhor.',
  'Segunda leitura rápida vale mais que primeira leitura lenta.',
  'PDF de 400 páginas se vence com divisão e ritmo.',
  'A página de hoje é a revisão da semana que vem.',
  'Sublinhe a exceção: é ela que a banca cobra.',
  // 221-230 · lei e jurisprudência
  'Letra de lei se lê com os olhos e se fixa com questões.',
  'Súmula recitada de cabeça é ponto quase garantido.',
  'Jurisprudência recente é o tempero favorito da banca.',
  'Ler a lei seca cansa; perder ponto por preguiça cansa mais.',
  'O artigo que você pulou é o que cai.',
  'Decoreba com método tem nome: repetição espaçada.',
  'Prazo, competência e exceção: o trio que decide questões.',
  'Uma lei por semana em áudio nos deslocamentos.',
  'Quem lê o inciso completo não cai na paráfrase maliciosa.',
  'Copiar o artigo à mão uma vez vale três leituras.',
  // 231-240 · redação e discursivas
  'Redação se treina antes de precisar dela.',
  'Uma discursiva por semana constrói a nota da segunda fase.',
  'Estrutura salva quem trava: introdução, desenvolvimento, arremate.',
  'Letra legível é gentileza com o examinador — e com sua nota.',
  'Vocabulário de prova se colhe lendo boas respostas.',
  'Quem escreve todo dia não teme a folha em branco.',
  'Treine com limite de linhas: a banca vai impor o dela.',
  'Rascunho de esquema antes do texto: metade da nota está aí.',
  'Discursiva é argumento organizado, não enfeite.',
  'Releia sua redação um dia depois: o erro aparece sozinho.',
  // 241-250 · matemática e exatas
  'Exatas se aprende com o lápis, não com os olhos.',
  'Errar conta de cabeça na prova é caro: escreva os passos.',
  'RLM diário de dez minutos destrava mais que aulão mensal.',
  'Fórmula sem exercício evapora em uma semana.',
  'A calculadora da prova é você bem treinado.',
  'Refaça a questão que errou até ela ficar óbvia.',
  'Estatística cai em todo canto: não a deixe para depois.',
  'Quem domina porcentagem domina meia prova de raciocínio.',
  'Velocidade em exatas é subproduto de repetição.',
  'O problema difícil de hoje é o padrão reconhecível de amanhã.',
  // 251-260 · informática e atualidades
  'Informática decoreba? Não: é prática guiada por questões.',
  'Atalhos de teclado caem — e você usa todos os dias sem notar.',
  'Atualidades se acumulam: quinze minutos por dia, nunca na véspera.',
  'Leia a notícia e pergunte: como a banca cobraria isso?',
  'Segurança da informação é o novo queridinho das provas.',
  'Resumo mensal de atualidades vale mais que jornal diário solto.',
  'Quem entende o conceito não decora o botão.',
  'Nuvem, redes e planilhas: o tripé que sempre volta.',
  'Uma questão de informática por dia mantém o assunto morno.',
  'Atualidade sem fonte confiável é boato estudado.',
  // 261-270 · finanças e sacrifício
  'O investimento com maior retorno da sua vida é a sua preparação.',
  'Cada "não" a um rolê é um "sim" adiantado à posse.',
  'Sacrifício com prazo é escolha; sem prazo é martírio. Tenha plano.',
  'O curso caro não estuda por você.',
  'A recompensa de sábado é proporcional à semana cumprida.',
  'Diga à família o seu horário: apoio começa com informação.',
  'Abrir mão hoje é assinar o contracheque de depois.',
  'Vida social não morre: hiberna com hora marcada.',
  'Quem entende o porquê aguenta quase qualquer como.',
  'O preço da preparação se paga uma vez; o da desistência, todo ano.',
  // 271-280 · inteligência emocional
  'Resultado de prova não define seu valor; define seu próximo plano.',
  'Frustração é informação: o que ela está te pedindo para ajustar?',
  'Celebre as pequenas vitórias: o cérebro repete o que é premiado.',
  'Inveja do aprovado? Transforme em pergunta: o que ele fez por dia?',
  'Paciência é competência de concurseiro.',
  'Gratidão pelo que já aprendeu combate o desespero pelo que falta.',
  'Você aguenta mais do que pensa e precisa de menos do que teme.',
  'Um bom choro e de volta ao cronograma.',
  'Não decida nada importante depois de um simulado ruim.',
  'Equilíbrio emocional vale questões na hora do aperto.',
  // 281-290 · ambiente e ferramentas
  'Mesa limpa, edital claro.',
  'Fone com ruído branco: biblioteca portátil.',
  'Deixe o material da manhã pronto na noite anterior.',
  'O melhor app de foco é a porta fechada.',
  'Luz boa e cadeira decente são investimento, não luxo.',
  'Estude no mesmo lugar e o cérebro entra em modo prova sozinho.',
  'Papel e caneta ao lado: captura rápida, distração curta.',
  'Modo avião é o botão de aprovação do celular.',
  'Um cronômetro visível muda o comportamento.',
  'Ambiente que convida ao estudo economiza força de vontade.',
  // 291-300 · consistência avançada
  'Semana 40 é construída na semana 1.',
  'Não quebre a corrente duas vezes seguidas: regra de ouro do hábito.',
  'O difícil é começar; o impossível é colher sem plantar.',
  'Excelência é o hábito disfarçado de talento.',
  'Faça o futuro te encontrar estudando.',
  'A sorte do aprovado tem cheiro de rotina.',
  'Todo dia útil é dia útil para a vaga.',
  'Não conte os dias: faça os dias contarem horas líquidas.',
  'Quem estuda nas ondas baixas surfa as ondas altas.',
  'Persistência é repetir o ordinário até virar extraordinário.',
  // 301-310 · véspera de ciclo novo
  'Ciclo fechado, autoestima em dia.',
  'Fim de ciclo é espelho: o que o próximo precisa mudar?',
  'Comemore o ciclo completo antes de abrir o próximo.',
  'Cada ciclo fechado é uma volta a menos até a chegada.',
  'Ajuste um parafuso por ciclo, não o motor inteiro.',
  'O ciclo não precisa ser perfeito, precisa ser fechado.',
  'Balanço semanal honesto vale um coach.',
  'Domingo à noite: quinze minutos de planejamento, semana inteira de clareza.',
  'Repetir o ciclo certo é mais valioso que inventar um novo.',
  'Ciclos pequenos, promessas cumpríveis.',
  // 311-320 · prova de resistência
  'Provas longas se vencem com treino de resistência, não só de conteúdo.',
  'Cinco horas de prova pedem cinco horas de simulado sentado.',
  'Alimente-se na prova como treinou em casa: sem novidades.',
  'Gerencie a prova como um ciclo: fáceis primeiro, difíceis marcadas.',
  'Ansiedade nos primeiros dez minutos é normal: siga o protocolo.',
  'Marcar e pular é coragem tática.',
  'A questão 1 não define a prova. A 120 também não.',
  'Cartão de resposta com calma: pressa aqui custa caro.',
  'Treine a transição entre matérias: a prova não avisa.',
  'Quem simulou o dia inteiro não estranha o dia real.',
  // 321-330 · pós-edital
  'Edital publicado: o plano vira lei pessoal.',
  'Pós-edital é sprint com mapa: siga o conteúdo programático.',
  'Saiu o edital? Respira, lê duas vezes, replaneja uma.',
  'No pós-edital, o mais organizado dispara.',
  'Verticalize o edital e estude com checklist.',
  'Oitenta dias bem geridos mudam uma classificação.',
  'Pós-edital não é hora de material novo, é hora de intensidade.',
  'A banca definiu as regras; agora é execução.',
  'Cada tópico do edital riscado é dopamina legítima.',
  'Inscrição paga, compromisso dobrado.',
  // 331-340 · sabedoria geral
  'Quem entende o conceito improvisa; quem decora trava.',
  'Ensine alguém e aprenda duas vezes.',
  'Pergunta boa vale mais que resposta decorada.',
  'Estudar é ato de esperança com método.',
  'Conhecimento acumulado nunca é desperdício, mesmo mudando de edital.',
  'O cérebro adora história: transforme o artigo em caso concreto.',
  'Analogia boa fixa melhor que repetição burra.',
  'Interligue matérias: a prova é uma só.',
  'Curiosidade transforma obrigação em interesse.',
  'Entender o porquê da regra é decorar de graça.',
  // 341-350 · humor de concurseiro
  'Café coado, edital aberto: liturgia matinal.',
  'Seu par de neurônios favoritos agradece a revisão de hoje.',
  'Concurseiro raiz sonha com nota de corte — literalmente.',
  'O sofá chama? Diga que você liga depois da sessão.',
  'VADE MECUM: o peso no braço que vira peso na nota.',
  'Grupo de estudos bom é o que estuda mais do que conversa.',
  'Se decorar prazo fosse fácil, todo mundo passava.',
  'Feriado: palavra que o edital desconhece.',
  'Modo monge ativado: distrações em silêncio absoluto.',
  'Post-it na geladeira também é técnica de fixação.',
  // 351-360 · reta de chegada mental
  'Visualize a rotina do cargo, não só a festa da posse.',
  'A banca testa preparo; a jornada testa caráter. Você treina os dois.',
  'Não pare na iminência: muitos desistem a um edital da vaga.',
  'O sobrenome da aprovação é continuidade.',
  'Sua vaga está sendo construída agora, nesta sessão.',
  'Um passo hoje, um degrau amanhã, um cargo depois.',
  'O improvável de hoje é o óbvio retroativo da posse.',
  'Enquanto há edital, há caminho.',
  'Prepare-se tanto que a sorte fique constrangida de faltar.',
  'A caneta que assina sua posse está ficando sem tinta de tanto esperar? Estude.',
  // 361-366 · fechamento do ano
  'Ano virando: o edital do próximo já está sendo escrito. Você também.',
  'Balanço anual honesto: horas somadas, lições anotadas, rumo mantido.',
  'O dezembro de quem estudou é mais leve que o janeiro de quem prometeu.',
  'Feche o ano com gratidão pelas horas e fome pelas que faltam.',
  'Ano novo não apaga dívida de revisão: transfere. Melhor pagar em dia.',
  'O dia 366 existe para quem não deixa nada para depois.',
];
